# -*- coding: utf-8 -*-
"""Breast Cancer Wisconsin (Diagnostic) Data Set

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/187VHncnmjmWKorfjjYZ85yhFH8LqAMs0
"""

# Importation des bibliothèques nécessaires
import pandas as pd

# Chargement du fichier CSV
# Assure-toi que le fichier 'data.csv' est uploadé dans Colab
from google.colab import files
uploaded = files.upload()

# Lecture du CSV
df = pd.read_csv("data.csv")  # Remplace "data.csv" si ton fichier a un autre nom

# Affichage des premières lignes du fichier
print("Aperçu du dataset :")
print(df.head())

# Description statistique des colonnes numériques
print("\nDescription statistique :")
print(df.describe())

# Informations générales sur le dataset (types, valeurs nulles, etc.)
print("\nInformations sur le dataset :")
print(df.info())

# Résumé du dataset
print("\nRésumé des colonnes :")
for col in df.columns:
    print(f"{col} : {df[col].nunique()} valeurs uniques, {df[col].isnull().sum()} valeurs manquantes")

# Optionnel : affichage de la répartition des catégories pour les colonnes non numériques
print("\nRépartition des colonnes non numériques :")
for col in df.select_dtypes(include='object').columns:
    print(f"\nColonne {col} :")
    print(df[col].value_counts())

# Importation des bibliothèques nécessaires
import pandas as pd

# Aperçu des premières lignes
print("Aperçu du dataset :")
print(df.head())

# Description statistique des colonnes numériques
print("\nDescription statistique :")
print(df.describe())

# Informations générales
print("\nInformations sur le dataset :")
print(df.info())

import matplotlib.pyplot as plt

# Histogrammes
df.hist(figsize=(12,8), bins=15, color='skyblue')
plt.suptitle("Distribution des colonnes numériques")
plt.show()

# Boxplots pour détecter les valeurs extrêmes
df.plot(kind='box', figsize=(12,6), vert=False, color='orange')
plt.title("Boxplots des colonnes numériques")
plt.show()

import seaborn as sns

# Exclure les colonnes non numériques et les colonnes avec des valeurs manquantes/identifiants
df_numeric = df.drop(columns=['id', 'diagnosis', 'Unnamed: 32'])

# Calcul des corrélations pour les colonnes numériques
corr = df_numeric.corr()

# Heatmap
plt.figure(figsize=(12,10))
sns.heatmap(corr, annot=False, cmap='coolwarm', fmt=".2f")
plt.title("Matrice de corrélation")
plt.show()

# Graphique des colonnes non numériques
for col in df.select_dtypes(include='object').columns:
    plt.figure(figsize=(8,4))
    sns.countplot(y=df[col], palette='pastel')
    plt.title(f"Répartition des valeurs de {col}")
    plt.show()